project_name: whoAMI-scanner
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: main.go
    binary: whoAMI-scanner
